"""Skill Manage Tool — autonomous `SKILL.md` creation / patch / view.

Writes agentskills.io-compatible SKILL.md bundles into either
``~/.kohakuterrarium/skills/<name>/SKILL.md`` (``scope='user'``, default)
or ``<cwd>/.kt/skills/<name>/SKILL.md`` (``scope='project'``).

Actions:

- ``create``: new skill; refuses to overwrite unless ``allow_overwrite``.
- ``patch``: edit the body; frontmatter is preserved. Modes:
  ``replace`` (default) or ``append`` (adds dated section).
- ``view``: return SKILL.md content as text.

Config-snippet usage::

    tools:
      - name: skill_manage
        type: custom
        module: kt_biome.tools.skill_manage
        class_name: SkillManageTool
        options:
          default_scope: user       # user | project
          user_root: ~/.kohakuterrarium/skills
          project_root: .kt/skills
          allow_overwrite: false

Pairs with ``kt_biome.triggers.skill_nudge`` which fires periodic
"consider saving a skill" hints and silences itself once this tool is
used.
"""

import re
from pathlib import Path
from typing import Any

from kohakuterrarium.modules.tool.base import BaseTool, ExecutionMode, ToolResult
from kohakuterrarium.prompt.skill_loader import parse_frontmatter
from kohakuterrarium.utils.logging import get_logger

from kt_biome.tools import _skill_activity
from kt_biome.tools._skill_io import atomic_write, iso_now, serialize_skill

logger = get_logger(__name__)

# agentskills.io spec: lowercase, hyphen-separated, starting with a letter.
_NAME_RE = re.compile(r"^[a-z][a-z0-9-]*$")
_MAX_BODY_CHARS = 10_000
_DEFAULT_LICENSE = "internal"
_ACTIONS = ("create", "patch", "view")
_SCOPES = ("user", "project")
_MERGE_MODES = ("replace", "append")

_DOCUMENTATION = """# skill_manage

Create, patch, or view a reusable skill as `<root>/<name>/SKILL.md`.

## Actions
- `create(name, description, body, scope?)` — new bundle. Refuses to
  overwrite an existing one.
- `patch(name, new_body, scope?, merge_mode?)` — `replace` (default)
  rewrites the body; `append` adds a dated `## Update` section.
- `view(name, scope?)` — return SKILL.md content.

## Parameters
- `name`: `[a-z][a-z0-9-]*`.
- `scope`: `'user'` (default) or `'project'`.
- `body` / `new_body`: markdown, max 10 000 chars.

## When to use
After completing a non-trivial procedure the user (or a future you)
might redo, call `create` to save it. If a similar skill already
exists, `patch` it with new lessons.
"""


class SkillManageTool(BaseTool):
    """Create / patch / view skill bundles written as ``<name>/SKILL.md``."""

    needs_context = True
    # Writes SKILL.md atomically; two concurrent ``create`` / ``patch``
    # calls against the same skill would race on file contents.
    is_concurrency_safe = False
    # Appear before the autogenerated tool list so the model reads the
    # "save what you learn" nudge before it sees the tool entry.
    prompt_contribution_bucket = "first"

    def prompt_contribution(self) -> str:
        """Nudge the model to persist non-trivial procedures as skills.

        Pairs with the ``skill_nudge`` trigger, which silences itself
        once ``skill_manage`` is used. The prose is deliberately short:
        one "when to save", one "when to patch", one "where it lands".
        """
        return (
            "If you just finished a non-trivial procedure the user (or a "
            "future you) might redo, call `skill_manage` with "
            '`action="create"` to save it. If a similar skill already '
            'exists, `action="patch"` it with the new lesson. Skills '
            "land under `~/.kohakuterrarium/skills/<name>/SKILL.md` "
            "(user scope) or `./.kt/skills/<name>/SKILL.md` (project "
            "scope) and become immediately reachable via `##skill "
            "<name>##` / `/<name>`."
        )

    def __init__(
        self,
        config: Any = None,
        options: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(config)
        opts = options or {}
        self._default_scope = str(opts.get("default_scope", "user"))
        self._user_root = Path(
            opts.get("user_root", "~/.kohakuterrarium/skills")
        ).expanduser()
        self._project_root = Path(opts.get("project_root", ".kt/skills"))
        self._allow_overwrite = bool(opts.get("allow_overwrite", False))

    # ── Tool protocol ──────────────────────────────────────────────────

    @property
    def tool_name(self) -> str:
        return "skill_manage"

    @property
    def description(self) -> str:
        return (
            "Create, patch, or view a SKILL.md bundle under "
            "~/.kohakuterrarium/skills/<name>/ (or .kt/skills/<name>/ for "
            "project scope). Use to persist reusable procedures."
        )

    @property
    def execution_mode(self) -> ExecutionMode:
        return ExecutionMode.DIRECT

    def get_parameters_schema(self) -> dict[str, Any]:
        s = {"type": "string"}
        props: dict[str, Any] = dict.fromkeys(
            ("name", "description", "body", "new_body"), s
        )
        props["action"] = {"type": "string", "enum": list(_ACTIONS)}
        props["scope"] = {"type": "string", "enum": list(_SCOPES)}
        props["merge_mode"] = {"type": "string", "enum": list(_MERGE_MODES)}
        return {"type": "object", "properties": props, "required": ["action", "name"]}

    # ── Dispatch ───────────────────────────────────────────────────────

    async def _execute(self, args: dict[str, Any], **kwargs: Any) -> ToolResult:
        action = str(args.get("action", "")).strip()
        name = str(args.get("name", "")).strip()
        scope = str(args.get("scope") or self._default_scope)
        context = kwargs.get("context")
        agent_name = getattr(context, "agent_name", "") or "default"

        err = self._validate(action, name, scope)
        if err is not None:
            return err

        try:
            match action:
                case "create":
                    result = self._do_create(
                        name=name,
                        description=str(args.get("description", "")).strip(),
                        body=str(args.get("body", "")),
                        scope=scope,
                        context=context,
                    )
                case "patch":
                    result = self._do_patch(
                        name=name,
                        new_body=str(args.get("new_body", "")),
                        merge_mode=str(args.get("merge_mode", "replace")),
                        scope=scope,
                        context=context,
                    )
                case _:  # view
                    result = self._do_view(name=name, scope=scope, context=context)
        except Exception as exc:  # unexpected — log and surface cleanly
            logger.error(
                "skill_manage failed", action=action, skill=name, error=str(exc)
            )
            return ToolResult(error=f"skill_manage error: {exc}")

        if result.error is None:
            _skill_activity.mark_used(agent_name)
        return result

    def _validate(self, action: str, name: str, scope: str) -> ToolResult | None:
        if action not in _ACTIONS:
            return ToolResult(error=f"Unknown action: {action!r}")
        if not _NAME_RE.match(name):
            return ToolResult(
                error=(
                    f"Invalid skill name {name!r}: must match "
                    "[a-z][a-z0-9-]* (lowercase, hyphens allowed, "
                    "cannot start with a digit)."
                )
            )
        if scope not in _SCOPES:
            return ToolResult(error=f"Invalid scope: {scope!r}")
        return None

    # ── Implementations ───────────────────────────────────────────────

    def _do_create(
        self,
        *,
        name: str,
        description: str,
        body: str,
        scope: str,
        context: Any,
    ) -> ToolResult:
        if not description:
            return ToolResult(error="create requires a 'description'.")
        if len(body) > _MAX_BODY_CHARS:
            return ToolResult(
                error=f"body too large ({len(body)} chars, max {_MAX_BODY_CHARS})"
            )

        target = self._skill_path(name, scope=scope, context=context)
        if target.exists() and not self._allow_overwrite:
            return ToolResult(
                error=(
                    f"Skill {name!r} already exists at {target}. "
                    "Use action='patch' to edit, or enable allow_overwrite."
                )
            )

        metadata: dict[str, Any] = {
            "name": name,
            "description": description,
            "license": _DEFAULT_LICENSE,
            "created_at": iso_now(),
        }
        atomic_write(target, serialize_skill(metadata, body))
        logger.info("skill created", skill=name, scope=scope, path=str(target))
        return ToolResult(
            output=f"Created skill {name!r} at {target}",
            exit_code=0,
            metadata={"path": str(target), "scope": scope},
        )

    def _do_patch(
        self,
        *,
        name: str,
        new_body: str,
        merge_mode: str,
        scope: str,
        context: Any,
    ) -> ToolResult:
        if merge_mode not in _MERGE_MODES:
            return ToolResult(error=f"Invalid merge_mode: {merge_mode!r}")
        if len(new_body) > _MAX_BODY_CHARS:
            return ToolResult(
                error=(
                    f"new_body too large ({len(new_body)} chars, "
                    f"max {_MAX_BODY_CHARS})"
                )
            )

        target = self._skill_path(name, scope=scope, context=context)
        if not target.exists():
            return ToolResult(
                error=(
                    f"Skill {name!r} not found at {target}. "
                    "Use action='create' first."
                )
            )

        metadata, existing_body = parse_frontmatter(target.read_text(encoding="utf-8"))
        if not metadata:
            # File had no frontmatter — start a minimal one.
            metadata = {"name": name, "description": "", "license": _DEFAULT_LICENSE}

        if merge_mode == "replace":
            body = new_body
        else:
            suffix = f"\n\n## Update {iso_now()}\n\n{new_body}".rstrip() + "\n"
            body = existing_body.rstrip() + suffix
            if len(body) > _MAX_BODY_CHARS:
                return ToolResult(
                    error=(
                        f"merged body too large ({len(body)} chars, "
                        f"max {_MAX_BODY_CHARS}) — consider 'replace'."
                    )
                )

        metadata["updated_at"] = iso_now()
        atomic_write(target, serialize_skill(metadata, body))
        logger.info(
            "skill patched",
            skill=name,
            scope=scope,
            merge_mode=merge_mode,
            path=str(target),
        )
        return ToolResult(
            output=f"Patched skill {name!r} ({merge_mode}) at {target}",
            exit_code=0,
            metadata={"path": str(target), "merge_mode": merge_mode},
        )

    def _do_view(self, *, name: str, scope: str, context: Any) -> ToolResult:
        target = self._skill_path(name, scope=scope, context=context)
        if not target.exists():
            return ToolResult(error=f"Skill {name!r} not found at {target}.")
        logger.debug("skill viewed", skill=name, scope=scope)
        return ToolResult(
            output=target.read_text(encoding="utf-8"),
            exit_code=0,
            metadata={"path": str(target)},
        )

    # ── Helpers ────────────────────────────────────────────────────────

    def _skill_path(self, name: str, *, scope: str, context: Any) -> Path:
        """Resolve ``<root>/<name>/SKILL.md`` for the chosen scope."""
        if scope == "user":
            root = self._user_root
        else:
            root = self._project_root
            if not root.is_absolute():
                working_dir = getattr(context, "working_dir", None)
                base = Path(working_dir) if working_dir else Path.cwd()
                root = base / root
        return root / name / "SKILL.md"

    def get_full_documentation(self, tool_format: str = "native") -> str:
        return _DOCUMENTATION
